### PR TITLE
update version

### PR DESCRIPTION
**Pull request by ankur-dwivedi**

### CODE REVIEW

**Review by ahnv — COMMENTED** [review]
Has the testing concluded?

**Comment by ankur-dwivedi** [comment]
yes here's the testing video https://www.loom.com/share/29e7a604dc034eb7be7477ba5290e056

**Review by ahnv — APPROVED** [review]

**Comment by ahnv** [comment]
Please bump the following to 4.1.3
- Stable tag in readme.txt
- version in imagekit.php

Also update Changelog also in readme

**Comment by ankur-dwivedi** [comment]
> Please bump the following to 4.1.3
> 
> * Stable tag in readme.txt
> * version in imagekit.php
> 
> Also update Changelog also in readme

done addressed in this [commit](https://github.com/imagekit-developer/imagekit-wordpress/pull/1/commits/ff1444ff6f5d08853ae7c89ba8c86d6f5f4b68a1)

**Pull request merged**
